# IDEAS

i_list_ideas:
    pattern:  /ideas
    defaults: { _controller: metaIdeaProfileBundle:Default:list, max: 10 }

i_new_idea:
    pattern:  /ideas/new
    defaults: { _controller: metaIdeaProfileBundle:Default:create}

i_show_idea:
    pattern:  /idea/{id}/{slug}
    defaults: { _controller: metaIdeaProfileBundle:Default:show, slug: _}
    requirements:
        id: \d+

i_edit_idea:
    pattern:  /idea/edit/{id}
    defaults: { _controller: metaIdeaProfileBundle:Default:edit }
    requirements:
        id: \d+
        _method:  POST

# Watching ideas
i_watch_idea:
    pattern:  /watch/idea/{id}
    defaults: { _controller: metaIdeaProfileBundle:Default:watch }

i_unwatch_idea:
    pattern:  /unwatch/idea/{id}
    defaults: { _controller: metaIdeaProfileBundle:Default:unwatch }

