# IDEAS

i_list_ideas:
    pattern:  /ideas
    defaults: { _controller: metaIdeaProfileBundle:Default:list, max: 10, archived: false }

i_list_archived_ideas:
    pattern:  /ideas/archived
    defaults: { _controller: metaIdeaProfileBundle:Default:list, max: 10, archived: true }

i_new_idea:
    pattern:  /ideas/new
    defaults: { _controller: metaIdeaProfileBundle:Default:create}

i_show_idea:
    pattern:  /idea/show/{id}/{slug}
    defaults: { _controller: metaIdeaProfileBundle:Default:show, slug: _}
    requirements:
        id: \d+

i_show_idea_concept:
    pattern:  /idea/concept/{id}/{slug}
    defaults: { _controller: metaIdeaProfileBundle:Default:showConceptOrKnowledge, slug: _, type: 'concept'}
    requirements:
        id: \d+

i_show_idea_knowledge:
    pattern:  /idea/knowledge/{id}/{slug}
    defaults: { _controller: metaIdeaProfileBundle:Default:showConceptOrKnowledge, slug: _, type: 'knowledge'}
    requirements:
        id: \d+

i_show_idea_timeline:
    pattern:  /idea/timeline/{id}/{slug}/{page}
    defaults: { _controller: metaIdeaProfileBundle:Default:showTimeline, slug: _, page: 1}
    requirements:
        id: \d+

i_edit_idea:
    pattern:  /idea/edit/{id}
    defaults: { _controller: metaIdeaProfileBundle:Default:edit }
    requirements:
        id: \d+
        _method:  POST

i_edit_idea_reset_picture:
    pattern:  /idea/resetpicture/{id}
    defaults: { _controller: metaIdeaProfileBundle:Default:resetPicture }
    requirements:
        id: \d+

i_delete_idea:
    pattern:  /idea/delete/{id}
    defaults: { _controller: metaIdeaProfileBundle:Default:delete }
    requirements:
        id: \d+

i_archive_idea:
    pattern:  /idea/archive/{id}
    defaults: { _controller: metaIdeaProfileBundle:Default:archiveOrRecycle, archive: true }
    requirements:
        id: \d+

i_recycle_idea:
    pattern:  /idea/recycle/{id}
    defaults: { _controller: metaIdeaProfileBundle:Default:archiveOrRecycle, archive:false }
    requirements:
        id: \d+

# COMMENTS
i_show_idea_comment:
    pattern:  /idea/timeline/comment/{id}
    defaults: { _controller: metaIdeaProfileBundle:Default:addIdeaComment }
    requirements:
      id: \d+

# Watching ideas
i_watch_idea:
    pattern:  /watch/idea/{id}
    defaults: { _controller: metaIdeaProfileBundle:Default:watch }
    requirements:
        id: \d+

i_unwatch_idea:
    pattern:  /unwatch/idea/{id}
    defaults: { _controller: metaIdeaProfileBundle:Default:unwatch }
    requirements:
        id: \d+

# Add participant to an idea
i_add_participant_to_idea:
    pattern:  /idea/edit/{id}/add_participant/{username}
    defaults: { _controller: metaIdeaProfileBundle:Default:addParticipant }
    requirements:
        id: \d+

i_remove_participant_to_idea:
    pattern:  /idea/edit/{id}/remove_participant/{username}
    defaults: { _controller: metaIdeaProfileBundle:Default:removeParticipant }
    requirements:
        id: \d+

# Turn idea to project

i_turn_idea_into_project:
    pattern:  /idea/projectize/{id}
    defaults: { _controller: metaIdeaProfileBundle:Default:projectize }
    requirements:
        id: \d+