login:
    pattern: /login
    defaults: { _controller: metaUserProfileBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

invite:
    pattern: /invite
    defaults: { _controller: metaUserProfileBundle:Security:invite }

reactivate:
    pattern: /reactivate
    defaults: { _controller: metaUserProfileBundle:Security:reactivateOrRecover, flavour: reactivate }

recover:
    pattern: /recover
    defaults: { _controller: metaUserProfileBundle:Security:reactivateOrRecover, flavour: recover }

change_password:
    pattern: /change/password/{token}
    defaults: { _controller: metaUserProfileBundle:Security:changePassword }

u_signup:
    pattern:  /signup/{inviteToken}
    defaults: { _controller: metaUserProfileBundle:Default:create, inviteToken: null }

u_me:
    pattern:  /me
    defaults: { _controller: metaUserProfileBundle:Default:showMe }

u_show_user_profile:
    pattern:  /who/{username}
    defaults: { _controller: metaUserProfileBundle:Default:show }
    requirements:
        _method:  GET

u_show_user_dashboard:
    pattern:  /dashboard
    defaults: { _controller: metaUserProfileBundle:Default:showDashboard }
    requirements:
        _method:  GET

u_edit_user_profile:
    pattern:  /who/{username}
    defaults: { _controller: metaUserProfileBundle:Default:edit }
    requirements:
        _method:  POST

u_edit_user_profile_reset_avatar:
    pattern:  /who/{username}/resetavatar
    defaults: { _controller: metaUserProfileBundle:Default:resetAvatar }

u_delete_user_profile:
    pattern:  /byebye/{username}
    defaults: { _controller: metaUserProfileBundle:Default:delete }
    requirements:
        _method:  GET

u_list_users:
    pattern:  /people/{page}/{sort}
    defaults: { _controller: metaUserProfileBundle:Default:list, page: 1, sort: newest }
    requirements:
        page: \d+
        sort: newest|update|active|alpha

u_choose_user:
    pattern:  /people/choose/{targetAsBase64}
    defaults: { _controller: metaUserProfileBundle:Default:choose }

u_follow_user:
    pattern:  /follow/{username}
    defaults: { _controller: metaUserProfileBundle:Default:followUser }

u_unfollow_user:
    pattern:  /unfollow/{username}
    defaults: { _controller: metaUserProfileBundle:Default:unfollowUser }


u_list_all_skills:
    pattern:  /skills
    defaults: { _controller: metaUserProfileBundle:Default:listSkills }
