general:
    resource: "@metaGeneralBundle/Resources/config/routing.yml"
    prefix:   /

meta_idea_profile:
    resource: "@metaIdeaProfileBundle/Resources/config/routing.yml"
    prefix:   /

meta_standard_project_profile:
    resource: "@metaStandardProjectProfileBundle/Resources/config/routing.yml"
    prefix:   /

meta_user_profile:
    resource: "@metaUserProfileBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
