parameters:
  idea.menu:
    timeline:
      icon: fa fa-comments
      route: i_show_idea_timeline
      private: false
    info:
      icon: fa fa-info-circle
      route: i_show_idea
      private: false
    content:
      icon: fa fa-book
      route: i_show_idea_content
      private: false
    settings:
      icon: fa fa-wrench
      route: i_show_idea_settings
      private: false